#!/bin/bash

cd ../cfltk

cmake -B bin -S . \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPTION_USE_SYSTEM_LIBPNG=OFF \
    -DOPTION_USE_SYSTEM_LIBJPEG=OFF \
    -DOPTION_USE_SYSTEM_ZLIB=OFF \
    -DOPTION_USE_GL=ON \
    -DFLTK_BUILD_EXAMPLES=OFF \
    -DFLTK_BUILD_TEST=OFF \
    -DOPTION_USE_THREADS=ON \
    -DOPTION_LARGE_FILE=ON \
    -DOPTION_BUILD_HTML_DOCUMENTATION=OFF \
    -DOPTION_BUILD_PDF_DOCUMENTATION=OFF \
    -CFLTK_BUILD_SHARED=ON \
    -DCMAKE_C_FLAGS="-fPIC" \
    -CMAKE_CXX_FLAGS="-fPIC" \
    -CMAKE_EXE_LINKER_FLAGS="-fPIC"

cmake --build bin
