#!/bin/bash

PACKAGE_NAME="quickjs-cffi"
PACKAGE_VER="0.1.0"

function prepare () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2

    # rm if existing
    local CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi

    if [ -d $CACHE_QUICKJS_FFI_PATH ]; then
        rm -rf CACHE_QUICKJS_FFI_PATH
    fi

    # clone
    git clone git@github.com:shajunxing/quickjs-ffi.git $CACHE_QUICKJS_FFI_PATH
    cp patched-quickjs-ffi-Makefile $CACHE_QUICKJS_FFI_PATH/Makefile
    echo prepare $PACKAGE_NAME $PACKAGE_VER
}

function build () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2

    # setup python venv
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    deactivate

    # build quickjs-ffi
    local CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi
    cd $CACHE_QUICKJS_FFI_PATH
    make

    echo build $PACKAGE_NAME $PACKAGE_VER
}

function install () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2
    local LOCAL_PACKAGE_PATH=$3
    
    # copy python venv
    cp -r $ENV_PATH/$CACHE_PACKAGE_PATH/venv $ENV_PATH/$LOCAL_PACKAGE_PATH/venv
    cp -r $ENV_PATH/$CACHE_PACKAGE_PATH/fake_include $ENV_PATH/$LOCAL_PACKAGE_PATH/fake_include
    cp -r $ENV_PATH/$CACHE_PACKAGE_PATH/fake_libc_include $ENV_PATH/$LOCAL_PACKAGE_PATH/fake_libc_include
    cp $ENV_PATH/$CACHE_PACKAGE_PATH/autogen.py $ENV_PATH/$LOCAL_PACKAGE_PATH/autogen.py

    # copy quickjs-ffi.js and quickjs-ffi.so
    local CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi
    cp $CACHE_QUICKJS_FFI_PATH/quickjs-ffi.js $ENV_PATH/$LOCAL_PACKAGE_PATH/quickjs-ffi.js
    cp $CACHE_QUICKJS_FFI_PATH/quickjs-ffi.so $ENV_PATH/$LOCAL_PACKAGE_PATH/quickjs-ffi.so
    cp $ENV_PATH/$CACHE_PACKAGE_PATH/qjs-cffi $ENV_PATH/qjs-cffi

    echo install $PACKAGE_NAME $PACKAGE_VER
}

function uninstall () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2
    local LOCAL_PACKAGE_PATH=$3

    # custom uninstall commands
    rm -f $ENV_PATH/qjs-cffi

    echo uninstall $PACKAGE_NAME $PACKAGE_VER
}

# dispatch function with args without $0 and $1
echo $($1 ${@:2})
