#!/bin/bash

PACKAGE_NAME="quickjs-cffi"
PACKAGE_VER="0.1.0"

function prepare () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi

    # rm if existing
    if [ -d $CACHE_QUICKJS_FFI_PATH ]; then
        rm -rf CACHE_QUICKJS_FFI_PATH
    fi

    # clone
    git clone git@github.com:shajunxing/quickjs-ffi.git $CACHE_QUICKJS_FFI_PATH
    cp patched-quickjs-ffi-Makefile $CACHE_QUICKJS_FFI_PATH/Makefile
    echo prepare $PACKAGE_NAME $PACKAGE_VER
}

function build () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi

    cd $CACHE_QUICKJS_FFI_PATH
    PATH=$PATH:../quickjs make

    echo build $PACKAGE_NAME $PACKAGE_VER
}

function install () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    LOCAL_PACKAGE_PATH=$3
    CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi
    LOCAL_PACKAGE_CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$LOCAL_PACKAGE_PATH/ffi

    mkdir -p $CACHE_QUICKJS_FFI_PATH
    cp $CACHE_QUICKJS_FFI_PATH/quickjs-ffi.js $CACHE_QUICKJS_FFI_PATH/quickjs-ffi.js
    cp $CACHE_QUICKJS_FFI_PATH/quickjs-ffi.so $CACHE_QUICKJS_FFI_PATH/quickjs-ffi.so

    echo install $PACKAGE_NAME $PACKAGE_VER
}

function uninstall () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    LOCAL_PACKAGE_PATH=$3
    CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi
    LOCAL_PACKAGE_CACHE_QUICKJS_FFI_PATH=$ENV_PATH/$LOCAL_PACKAGE_PATH/ffi

    rm -rf $CACHE_QUICKJS_FFI_PATH
    rm -rf $LOCAL_PACKAGE_CACHE_QUICKJS_FFI_PATH

    echo uninstall $PACKAGE_NAME $PACKAGE_VER
}

# dispatch function with args without $0 and $1
echo $($1 ${@:2})
