#!/bin/bash

PACKAGE_NAME="quickjs-cffi"
PACKAGE_VER="0.1.0"

function prepare () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    QUICKJS_FFI_PATH=$ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-ffi

    # rm if existing
    if [ -d $QUICKJS_FFI_PATH ]; then
        rm -rf QUICKJS_FFI_PATH
    fi

    # clone
    git clone git@github.com:shajunxing/quickjs-ffi.git QUICKJS_FFI_PATH


    echo prepare $PACKAGE_NAME $PACKAGE_VER
}

function build () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    echo build $PACKAGE_NAME $PACKAGE_VER
}

function install () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    LOCAL_PACKAGE_PATH=$3
    echo install $PACKAGE_NAME $PACKAGE_VER
}

function uninstall () {
    ENV_PATH=$1
    CACHE_PACKAGE_PATH=$2
    LOCAL_PACKAGE_PATH=$3
    QUICKJS_FFI_PATH=$CACHE_PACKAGE_PATH/quickjs-ffi
    rm -rf QUICKJS_FFI_PATH
    echo uninstall $PACKAGE_NAME $PACKAGE_VER
}

# dispatch function with args without $0 and $1
echo $($1 ${@:2})
